# 1. Introduction

In [3]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


NumPy is the core library for numerical computing in Python. It provides fast array operations.

# 2. Creating Arrays

In [4]:
# From list
arr1 = np.array([1, 2, 3, 4])

# Zeros and Ones
zeros = np.zeros((2, 3))
ones = np.ones((2, 2))

# Range
arr2 = np.arange(0, 10, 2)

# Linspace
arr3 = np.linspace(0, 1, 5)

print(arr1, zeros, ones, arr2, arr3)

[1 2 3 4] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


# 3. Array Properties

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Size:", arr.size)

Shape: (2, 3)
Dimensions: 2
Data type: int64
Size: 6


# 4. Reshaping Arrays

In [6]:
arr = np.arange(12)

reshaped = arr.reshape(3, 4)
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 5. Indexing & Slicing

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])        # First element
print(arr[-1])       # Last element
print(arr[1:4])      # Slice

10
50
[20 30 40]


# 2D Example

In [8]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2d[1,2])   # 6
print(arr2d[:,1])   # Column

6
[2 5 8]


 # 6. Mathematical Operations

In [9]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a * b)
print(np.sqrt(a))
print(np.mean(a))

[5 7 9]
[ 4 10 18]
[1.         1.41421356 1.73205081]
2.0


# 7. Broadcasting

In [10]:
arr = np.array([1,2,3])

print(arr + 5)  # Adds 5 to each element

[6 7 8]


Broadcasting allows operations on different-sized arrays.

# 8. Random Numbers# 

In [11]:
np.random.seed(42)

print(np.random.rand(3))
print(np.random.randint(1, 10, size=(2,2)))

[0.37454012 0.95071431 0.73199394]
[[5 7]
 [3 7]]


# 9. Filtering & Conditions

In [12]:
arr = np.array([10, 20, 30, 40])

filtered = arr[arr > 20]
print(filtered)

[30 40]


# 10. Iteration

In [13]:
arr = np.array([[1,2],[3,4]])

for x in np.nditer(arr):
    print(x)

1
2
3
4


# 11. Aggregation Functions

In [14]:
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

15
5
1
1.4142135623730951


# 12. Sorting & Searching 

In [15]:
arr = np.array([3,1,2])

print(np.sort(arr))
print(np.where(arr == 2))

[1 2 3]
(array([2]),)


# 13. Intermediate: Matrix Operations

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A, B))   # Matrix multiplication
print(np.transpose(A))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


# 14. Intermediate: Linear Algebra

In [17]:
A = np.array([[1,2],[3,4]])

print(np.linalg.det(A))   # Determinant
print(np.linalg.inv(A))   # Inverse

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


# 15. Real Use Case

In [18]:
# Simulate student scores
scores = np.random.randint(40, 100, 20)

print("Scores:", scores)
print("Average:", np.mean(scores))
print("Top Score:", np.max(scores))
print("Passed:", scores[scores >= 50])

Scores: [50 50 63 92 75 79 63 42 61 92 41 63 83 69 77 41 99 60 72 51]
Average: 66.15
Top Score: 99
Passed: [50 50 63 92 75 79 63 61 92 63 83 69 77 99 60 72 51]
